### ISSUE TITLE
Recent activity shows information related to wrong address

### ISSUE THREAD

**Issue by cjoliva** [TokelPlatform/tokel_dapp#134]
## Operation System

Linux Mint v19.3 (derived from Ubuntu 18.04)

## Expected Behavior

Display tokel info related to receiving wallet (mine) rather than sending wallet (discord).

## Current Behavior

I sent some Tokel from the discord group to my local wallet (TokelPlatform_linux_1.0.0.AppImage).  The balance in my local wallet is correct, but in two locations, it displays info relevant to the sending account, not the receiving account.  In the transaction below, my account ends with 4S and the sending/change account ends with 7P.
https://tokel.explorer.dexstats.info/tx/5c396e7bb9f95e1c12b26043d79a66bd13cdbd7d6cfb1de22136d6fb7448e415

## Steps to Reproduce

1.  Send tokel from Tokel discord system to local wallet.

2. After receiving, click on Dashboard | Total Holdings screen or Dashboard | Tokel | Recent Activities screen.  Info there is relevant to sending account, not receiving account.

## Possible Solution (Not obligatory)

![tokelerr1](https://user-images.githubusercontent.com/6606300/131592281-f5f82fce-f0f7-4b07-b684-d660684937fa.gif)
![tokelerr2](https://user-images.githubusercontent.com/6606300/131592283-8b9a3132-82ad-437e-a6fd-55fbcaab849b.gif)

**Comment by piggydoughnut** [comment]
Hey there @cjoliva ! Thanks a lot for reporting this. There is a bug in our transaction parsing algorithm which shows itself in all sorts of interesting ways :) New release will fix that. It would be great if you could test the new version when we have it before we make the official release to see if that bug is gone. I will keep you in the loop. Thx again for such a good bug report. 💪🏽 

It is our first bug report from a community memeber too 🐛

**Comment by cjoliva** [comment]
Sure.  I'd be happy to test.  Just notify me when the update is ready.

**Comment by DreamTrims** [comment]
@piggydoughnut maybe the same bug is causing the total balance not to update until you log out and log back in?

**Comment by piggydoughnut** [comment]
@cjoliva this should be resolved by the latest release. I will close it for now, feel free to reopen if it has not been resolved for you.
