### ISSUE TITLE
No History showing

### ISSUE THREAD

**Issue by Eilien-ILN** [TokelPlatform/tokel_dapp#222]
Transaction history not showing.

**Comment by piggydoughnut** [comment]
Hello, we need a bit more context. Transaction history for coins or for tokens? Transactions history for tokens is not implemented yet. 
When does it happen? Can you please fill in the bug report so we can get more context?

## Operation System




## Expected Behavior



## Current Behavior



## Steps to Reproduce





1.

2.

3.

4.

## Possible Solution (Not obligatory)

**Comment by NutellaLicka** [comment]
Suspect they are referring to this issue that is already captured:
https://github.com/TokelPlatform/tokel_dapp/issues/152

Extended part of that issue is showing token transactions apart from normal coin sends in the TKL coin history part of the dApp:
https://github.com/TokelPlatform/tokel_dapp/issues/196

**Comment by piggydoughnut** [comment]
Closing as no context has been given and as mentioned above we are probably already tracking this issue.
