### ISSUE TITLE
Identifier (ID, optional)

### ISSUE THREAD

**Issue by 1iamtoken** [TokelPlatform/tokel_dapp#223]
When I added a random ID [https://1iamtoken.com/wp-content/uploads/2021/11/Screenshot-2021-11-29-at-17.09.28.png](url) i got this message "failed to create NFT"

**Comment by piggydoughnut** [comment]
Hey, can you please specify what ID you entered? Also your screenshot does not seem to be showing.
Can you please fill in the bug report to give us more context?

## Operation System




## Expected Behavior



## Current Behavior



## Steps to Reproduce





1.

2.

3.

4.

## Possible Solution (Not obligatory)

**Comment by lenilsonjr** [comment]
Extra validation has been added to ensure user can't enter any invalid ones in #213
